### ISSUE TITLE
代码是不是少了出结果的部分？

### ISSUE THREAD

**Issue by rexchoi1983** [ProHiryu/bert-chinese-ner#1]
hello，有仔细看了您的代码，非常感谢能有这样的参考。有些疑问，源码上do_predict的部分是被前面检测过滤掉的，然后我开起来之后，跑起来是有问题的，包括读取输入，现在是读取text.txt，好像没什么意义吧，如果自己弄一些完整的句子，那么dataprocesser里面的_read_data不适用，我尝试改了这个方法，但得到的NER结果很诡异，比如，我输入“今天北京的天气真好。你说呢？是啊，北京天气难得那么好啊。”，得到的结果全部都是[CLS]，还望不吝赐教，非常感谢！

**Comment by ProHiryu** [comment]
predict文件应该以text.txt当中的形式存放，如果你想自定义输入方式你就写一个函数提取句子转变成BIO标注形式即可，text.txt当中的label是可以自定义的

当然你需要先做训练，产生了模型之后才能做predict，结果只需要看output/result_dir/label_test.txt就行了

**Comment by rexchoi1983** [comment]
谢谢！我再研究下的！

**Comment by AaronWhite95** [comment]
没有text.txt这个文件吧，说的是test.txt吗？如果自定义输入的话和需要对每个字都写一个label吗？

**Comment by sunlanchang** [comment]
> 没有text.txt这个文件吧，说的是test.txt吗？如果自定义输入的话和需要对每个字都写一个label吗？

应该是，自定义输入的话相当于得在test数据后加一个label占位符。
