### ISSUE TITLE
这个label的个数为啥要+1呢？

### ISSUE THREAD

**Issue by xljhtq** [ProHiryu/bert-chinese-ner#12]
![image](https://user-images.githubusercontent.com/30365798/53729577-8a7b1880-3eb0-11e9-8711-5b0944b0fc8e.png)

请问这里参数中为何num_labels=len(label_list) + 1，而不是num_labels=len(label_list) ？
照理‘X’这个label也是在原有的那个NerProcessor的get_labels函数中的，不应该哪里多出来一个label呀？请解答一下我的疑惑～

**Comment by snowlord** [comment]
因为补齐的的数据，也要进行标注。

**Comment by Chenny0808** [comment]
> 因为补齐的的数据，也要进行标注。
@snowlord ，要是为了补齐，补齐也不止才补齐一个字呀，怎么才加1，那也应该是 max_len-num_tag呢，有些费解呢

**Comment by nlp4whp** [comment]
> > 因为补齐的的数据，也要进行标注。
> > @snowlord ，要是为了补齐，补齐也不止才补齐一个字呀，怎么才加1，那也应该是 max_len-num_tag呢，有些费解呢

你可以理解为<pad>，作者源码里写的是**NULL**， 对应label_id是0
