### ISSUE TITLE
label2id.pkl

### ISSUE THREAD

**Issue by zhangshaodong** [ProHiryu/bert-chinese-ner#18]
能否提供一下label2id.pkl？

**Comment by ProHiryu** [comment]
这个是根据label在代码当中生成保存的，如果报错请检查是否创建了output文件夹

**Comment by huangxiancun** [comment]
感觉这个文件输出来是多余的啊，还是有其他作用？ 反正在main()函数里 ，最后预测的时候，在读取一下，是否加两行代码，然后 把这波读写操作注释掉？
label2id = {}
for (i, label) in enumerate(label_list, 1):
            label2id[label] = i

**Comment by ProHiryu** [comment]
是，这个文件本来就是给预测的时候用的，NLP里面都这样用
