### ISSUE TITLE
训练两步就停止了？

### ISSUE THREAD

**Issue by kFoodie** [ProHiryu/bert-chinese-ner#21]
![image](https://user-images.githubusercontent.com/16017418/56416174-ac92f380-62c2-11e9-9966-b0c24faeef8e.png)
我用自己的数据集，然后训练两步就停了，不清楚是什么原因。可以麻烦大神解答一下吗？万分感谢

**Comment by kFoodie** [comment]
从github上下载下来的也是这样。。

**Comment by ProHiryu** [comment]
有日志或者输出结果吗？还有运行时候的参数

**Comment by kFoodie** [comment]
没有啊。。

**Comment by Githubhgh** [comment]
flags.DEFINE_float("num_train_epochs", 3.0, "Total number of training epochs to perform.")
把这个3改成你要训练的次数就行了
