### ISSUE TITLE
请问下数据集来源是？train.txt这些

### ISSUE THREAD

**Issue by Vuscity** [ProHiryu/bert-chinese-ner#25]
目前自己有新闻语料，但是未标注，请问大佬们用什么工具进行BIO标注的呢？

**Comment by wshzd** [comment]
首先会有一个NER的列表，是两列（实体名称、实体类别），然后通过实体名称来扫描语料，对语料进行BIO三种类型按照字符维度打标签，比如：NER列表是：“中国”  ORG，如果给语料“我是中国人”进行BIO标注的话，结果是这样的：
我   O
是   O
中   B-ORG
国   I-ORG
人   O
因为只有中国在NER列表中，所以只有“中国”进行了BI标注，其他字都为O，最后的结果是需要通过python代码自己去实现的，NER列表是关键，希望能给你一些启示
