### ISSUE TITLE
请教大佬，关于BERT预训练

### ISSUE THREAD

**Issue by Vuscity** [ProHiryu/bert-chinese-ner#27]
问题1：
论文上说模型是预训练的，只需要在dev数据集上微调，那为什么还需要先在train数据集上训练呢？

问题2：
此模型的评估是基于dev数据集，没有基于test数据集是吗？

真心求教！谢谢

**Comment by ProHiryu** [comment]
1.dev和test本身就是一个概念，对于原来Google用于训练Bert的数据来说，我们的训练数据集就是所谓的dev集做微调
2.评估是只针对dev（data目录下的dev）

**Comment by Vuscity** [comment]
好的 谢谢~
