### ISSUE TITLE
训练好的模型如何调用

### ISSUE THREAD

**Issue by moonlione** [ProHiryu/bert-chinese-ner#28]
我训练好了实体识别的模型，但不知道如何调用这个模型。这里涉及到模型的调用，需要识别的文本怎么处理成模型需要的格式等问题。麻烦帮忙解答一下，万分感谢！

**Comment by dlNone** [comment]
你知道如何调用了吗？

**Comment by huangxiancun** [comment]
请 死磕 run_classifier.py这个文件，从代码的框架逻辑，从该代码的作用出发，从代码的写法 琢磨。 flags.do_train do_eval do_predict 要设置好，我们见到的几乎都finetuning操作，这个也不例外。所以 这个肯定又模型的调用，你可以看一下if flags.do_predict： 。

**Comment by yanfan0531** [comment]
> 请 死磕 run_classifier.py这个文件，从代码的框架逻辑，从该代码的作用出发，从代码的写法 琢磨。 flags.do_train do_eval do_predict 要设置好，我们见到的几乎都finetuning操作，这个也不例外。所以 这个肯定又模型的调用，你可以看一下if flags.do_predict： 。

你好我想问一下，我先do_train好了模型，再调用do_predict去预测，但是有时候会出很奇怪的结果，好像模型没有经过训练一样。。请问有遇到过这种情况吗，是不是它直接从init_checkpoint里，而不是output里训练好的模型恢复了？我在同时调用do_train和do_predict就不会这样，好奇怪

**Comment by ProHiryu** [comment]
可以检查一下是否存储了模型在output里面，主要是看看什么情况下会出现这种结果

Best Regards,
------------------------------------------------------------
HeQi Song (宋贺奇)
Data Scientist, Accenture Advanced Technology Centers, China

TEL: +86-18916376131
WEB: http://songheqi.me
E-mail: songheqi1996@gmail.com


yanfan0531 <notifications@github.com> 于2019年7月15日周一 下午12:01写道：
