### ISSUE TITLE
测试集和输出结果数量不一致

### ISSUE THREAD

**Issue by ILiangk** [ProHiryu/bert-chinese-ner#31]
我用自己的数据尝试跑了一下 test文件中有100条样例 最终label_text的输出却高于100，请问这是怎么回事

**Comment by HooFaya** [comment]
同样的问题，115test , 383label_text

**Comment by HooFaya** [comment]
> 同样的问题，115test , 383label_text

update:问题解决了，两个原因，1.训练不满一个epoch,2.CLS SEP占位

**Comment by jemmryx** [comment]
> > 同样的问题，115test , 383label_text
> 
> update:问题解决了，两个原因，1.训练不满一个epoch,2.CLS SEP占位
这个跟训练不满一个epoch有关吗？是不是因为在数据处理的时候，超过max_seq_length的句子都被截断了呢

**Comment by nuass** [comment]
替换保存代码为以下：

        def result_to_pair(writer):
            for predict_line, prediction in zip(predict_examples, result):
                idx = 0
                line = ''
                line_token = str(predict_line.text).split(' ')
                label_token = str(predict_line.label).split(' ')
                len_seq = len(label_token)
                if len(line_token) != len(label_token):
                    tf.logging.info(predict_line.text)
                    tf.logging.info(predict_line.label)
                    break
                for id in prediction:
                    if idx >= len_seq:
                        break
                    if id == 0:
                        continue
                    curr_labels = id2label[id]
                    if curr_labels in ['[CLS]', '[SEP]']:
                        continue
                    try:
                        line += line_token[idx] + ' ' + label_token[idx] + ' ' + curr_labels + '\n'
                    except Exception as e:
                        tf.logging.info(e)
                        tf.logging.info(predict_line.text)
                        tf.logging.info(predict_line.label)
                        line = ''
                        break
                    idx += 1
                writer.write(line + '\n')

        with codecs.open(output_predict_file, 'w', encoding='utf-8') as writer:
            result_to_pair(writer)
