### ISSUE TITLE
最大长度问题

### ISSUE THREAD

**Issue by jemmryx** [ProHiryu/bert-chinese-ner#35]
1.在数据处理的时候超过max_seq_length的句子都被截断了，那么预测的时候就会出现标签数量变少的问题。
2.test数据集按理应该是没有标签的，因此数据处理部分存在一定的缺失？

**Comment by ProHiryu** [comment]
这是bert的原生缺陷

**Comment by mingxixixi** [comment]
> 这是bert的原生缺陷
你好，为什么我把max_seq_length设置为510的时候，会报错呢
