### ISSUE TITLE
conlleval.pl文件怎么使用

### ISSUE THREAD

**Issue by zxp93** [ProHiryu/bert-chinese-ner#4]
因为想要输入句子，得到各个实体。
模型的f1是把单个的字合并成句子算的F1吗。

**Comment by ProHiryu** [comment]
f1通过tf_metrics来计算，直接算字的f1

**Comment by zxp93** [comment]
> f1通过tf_metrics来计算，直接算字的f1

好的，使用conlleval.pl计算的话有92±0.5的F1

**Comment by zhunipingan** [comment]
> > f1通过tf_metrics来计算，直接算字的f1
> 
> 好的，使用conlleval.pl计算的话有92±0.5的F1

请问怎么使用的.pl进行的计算呢
