### ISSUE TITLE
为什么没有输出召回率和F值呢？

### ISSUE THREAD

**Issue by Cung806** [ProHiryu/bert-chinese-ner#42]
I0717 06:42:58.134186 140155849557824 tpu_estimator.py:2286] global_step/sec: 2.81616
I0717 06:42:58.134613 140155849557824 tpu_estimator.py:2287] examples/sec: 90.1171
I0717 06:42:58.491854 140155849557824 tpu_estimator.py:2286] global_step/sec: 2.79538
I0717 06:42:58.492231 140155849557824 tpu_estimator.py:2287] examples/sec: 89.4523
I0717 06:42:58.493007 140155849557824 basic_session_run_hooks.py:606] Saving checkpoints for 1284 into ./output/result_dir/model.ckpt.
I0717 06:43:01.181317 140155849557824 estimator.py:368] Loss for final step: 522.48596.
I0717 06:43:01.188701 140155849557824 error_handling.py:101] training_loop marked as finished

**Comment by dh12306** [comment]
同求

**Comment by Lanme** [comment]
loss倒是可以在tensorboard里面看到，我想问下你们训练的结果，我预测text.txt的时候，参数加载来自model-ckpt-4749，但是结果有很多只有B-person，没有I-person?

**Comment by Lanme** [comment]
> loss倒是可以在tensorboard里面看到，我想问下你们训练的结果，我预测text.txt的时候，参数加载来自model-ckpt-4749，但是结果有很多只有B-person，没有I-person?

应该是数据集的问题，我打算用人民日报数据集试试先

**Comment by joinDonk** [comment]
你们训练了多久啊？跑了1天了？没看到收敛啊

**Comment by bingoc0207** [comment]
> I0717 06:42:58.134186 140155849557824 tpu_estimator.py:2286] global_step/sec: 2.81616
> I0717 06:42:58.134613 140155849557824 tpu_estimator.py:2287] examples/sec: 90.1171
> I0717 06:42:58.491854 140155849557824 tpu_estimator.py:2286] global_step/sec: 2.79538
> I0717 06:42:58.492231 140155849557824 tpu_estimator.py:2287] examples/sec: 89.4523
> I0717 06:42:58.493007 140155849557824 basic_session_run_hooks.py:606] Saving checkpoints for 1284 into ./output/result_dir/model.ckpt.
> I0717 06:43:01.181317 140155849557824 estimator.py:368] Loss for final step: 522.48596.
> I0717 06:43:01.188701 140155849557824 error_handling.py:101] training_loop marked as finished

你好，我最近也碰到了这个问题，可以问一下最后是怎么解决的吗   麻烦你了
