### ISSUE TITLE
why didn't have requirement.txt?

### ISSUE THREAD

**Issue by pymyself** [ProHiryu/bert-chinese-ner#45]
/Users/dr/.virtualenvs/Django面试/bin/python /Users/dr/PycharmProjects/bert-chinese-ner/tf_metrics.py
/Users/dr/.virtualenvs/Django面试/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/dr/.virtualenvs/Django面试/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/dr/.virtualenvs/Django面试/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/dr/.virtualenvs/Django面试/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/dr/.virtualenvs/Django面试/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/dr/.virtualenvs/Django面试/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

**Comment by ProHiryu** [comment]
只需要保证tensorflow版本在1.10左右就行

**Comment by pymyself** [comment]
好的 多谢回复🙏




| |
徐天洋
|
|
邮箱：18516012782@163.com
|

签名由 网易邮箱大师 定制

On 12/17/2019 16:59, songheqi wrote:

只需要保证tensorflow版本在1.10左右就行
