### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './output/label2id.pkl'

### ISSUE THREAD

**Issue by YerayL** [ProHiryu/bert-chinese-ner#48]
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7f74b46b78c8>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Using config: {'_model_dir': './output/result_dir/', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f74b22524a8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None), '_cluster': None}
INFO:tensorflow:_TPUContext: eval_on_tpu True
WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
Traceback (most recent call last):
  File "BERT_NER.py", line 621, in <module>
    tf.app.run()
  File "/home/lyy/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "BERT_NER.py", line 544, in main
    train_examples, label_list, FLAGS.max_seq_length, tokenizer, train_file)
  File "BERT_NER.py", line 296, in filed_based_convert_examples_to_features
    with open('./output/label2id.pkl','wb') as w:
FileNotFoundError: [Errno 2] No such file or directory: './output/label2id.pkl'

**Comment by xwjim** [comment]
请问下这个问题解决了么

**Comment by gaochaoqwe** [comment]
解决了吗老哥，我也遇到了这个错误

**Comment by waaaaaag** [comment]
没有解决，可能是tensorflow版本不同的原因

**Comment by waaaaaag** [comment]
> 解决了吗老哥，我也遇到了这个错误
没有解决，可能是tensorflow版本不同的原因

**Comment by waaaaaag** [comment]
> 解决了吗老哥，我也遇到了这个错误

没有解决，可能是tensorflow版本不同的原因

**Comment by wulinjuan** [comment]
我也遇到了，就是自己创建一个名字为output文件就可以了
