### ISSUE TITLE
TPU选项

### ISSUE THREAD

**Issue by AaronWhite95** [ProHiryu/bert-chinese-ner#5]
AttributeError: module 'tensorflow.contrib.tpu' has no attribute 'InputPipelineConfig'
跑代码报这个错，是只能在TPU下跑吗

**Comment by ProHiryu** [comment]
> AttributeError: module 'tensorflow.contrib.tpu' has no attribute 'InputPipelineConfig'
> 跑代码报这个错，是只能在TPU下跑吗

这个是TensorFlow安装或版本问题吧，我用的是最新的TensorFlow-gpu

**Comment by 2hip3ng** [comment]
你这个tensorflow的版本是多少啊

**Comment by shencunzailaozhang** [comment]
> > AttributeError: module 'tensorflow.contrib.tpu' has no attribute 'InputPipelineConfig'
> > 跑代码报这个错，是只能在TPU下跑吗
> 
> 这个是TensorFlow安装或版本问题吧，我用的是最新的TensorFlow-gpu

我想请问你如何在gpu中跑这个代码的，我已经把普通版tensorflow卸载了，安装了tensorflow-gpu，但是速度还是很慢，而且Tensorflow中也有提示“Running train on CPU”，所以我有点不确定到底是在GPU上还是在CPU上。还有一个问题，你跑完这个代码的训练部分大概花了多久呢？期待得到你的回复，谢谢。
