### ISSUE TITLE
ValueError: Dimensions must be equal, but are 17 and 11 for 'loss/mul' (op: 'Mul') with input shapes: [?,128,17], [?,128,11]

### ISSUE THREAD

**Issue by mingxixixi** [ProHiryu/bert-chinese-ner#50]
你好，我用自己的数据集运行的出现了这个错，请教一下这是哪里有问题呢？
ValueError: Dimensions must be equal, but are 17 and 11 for 'loss/mul' (op: 'Mul') with input shapes: [?,128,17], [?,128,11]

**Comment by ProHiryu** [comment]
需要检查你的标注类别，你的label有17个 内置是11个

**Comment by mingxixixi** [comment]
你好，那这个应该改哪里呢？



---Original---
