### ISSUE TITLE
你好，在测试集上的结果（精确率，召回率，F1值）没有输出吗

### ISSUE THREAD

**Issue by mingxixixi** [ProHiryu/bert-chinese-ner#53]
你好，在测试集上的结果（精确率，召回率，F1值）没有输出吗

**Comment by ProHiryu** [comment]
你可以手动输出的，调用函数获取即可

**Comment by bingoc0207** [comment]
> 你好，在测试集上的结果（精确率，召回率，F1值）没有输出吗

你好，打扰你了，我最近在看这个代码，试着运行了之后也没有发现prf值输出的地方，请问您最后是怎么算的呢，希望得到您的解答，麻烦您了
