### ISSUE TITLE
结果全为O问题

### ISSUE THREAD

**Issue by foreverxujiahuan** [ProHiryu/bert-chinese-ner#57]
用自己标注的数据去识别公司名，跑出来全为O，这可能是哪些原因导致的？

**Comment by ProHiryu** [comment]
1. 训练时间太短
2. 数据太稀疏

**Comment by tongbao96** [comment]
你预测的时候缺文件嘛

**Comment by foreverxujiahuan** [comment]
缺，自己创建个文件夹就好



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "baotongnoob"<notifications@github.com&gt;; 
发送时间: 2020年3月12日(星期四) 下午2:49
收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&gt;; 
抄送: "Lambda"<894463634@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)





 
你预测的时候缺文件嘛

**Comment by tongbao96** [comment]
wow,你在houston啊。那你当时换了自己标注的数据集 改了部分代码吗 还是直接上BIO标注的数据就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zzulixjh"<notifications@github.com&gt;; 
发送时间: 2020年3月12日(星期四) 下午3:28
收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&gt;; 
抄送: "baotong"<448276274@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)





 缺，自己创建个文件夹就好 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "baotongnoob"<notifications@github.com&amp;gt;;  
 发送时间: 2020年3月12日(星期四) 下午2:49 
 收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;gt;;  
 抄送: "Lambda"<894463634@qq.com&amp;gt;; "Author"<author@noreply.github.com&amp;gt;;  
 主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57) 
 
 
 
 
 
   
 你预测的时候缺文件嘛

**Comment by foreverxujiahuan** [comment]
不用改代码，保证BIO数据没问题就行


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"baotongnoob"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 下午3:30
收件人:&nbsp;"ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&gt;;
抄送:&nbsp;"Lambda"<894463634@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)





 wow,你在houston啊。那你当时换了自己标注的数据集 改了部分代码吗 还是直接上BIO标注的数据就行 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "zzulixjh"<notifications@github.com&amp;gt;;  
 发送时间: 2020年3月12日(星期四) 下午3:28 
 收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;gt;;  
 抄送: "baotong"<448276274@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57) 
 
 
 
 
 
  缺，自己创建个文件夹就好  
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "baotongnoob"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2020年3月12日(星期四) 下午2:49  
  收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;gt;;   
  抄送: "Lambda"<894463634@qq.com&amp;amp;gt;; "Author"<author@noreply.github.com&amp;amp;gt;;   
  主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)  
   
   
   
   
   
     
  你预测的时候缺文件嘛

**Comment by tongbao96** [comment]
怎么预测陌生的文本&nbsp; 它的测试集也打了标签的 然后预测的东西是测试集里的话&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zzulixjh"<notifications@github.com&gt;; 
发送时间: 2020年3月12日(星期四) 下午3:32
收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&gt;; 
抄送: "baotong"<448276274@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)





 不用改代码，保证BIO数据没问题就行 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"baotongnoob"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月12日(星期四) 下午3:30 
 收件人:&amp;nbsp;"ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Lambda"<894463634@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57) 
 
 
 
 
 
  wow,你在houston啊。那你当时换了自己标注的数据集 改了部分代码吗 还是直接上BIO标注的数据就行  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "zzulixjh"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2020年3月12日(星期四) 下午3:28  
  收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;gt;;   
  抄送: "baotong"<448276274@qq.com&amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;gt;;   
  主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)  
   
   
   
   
   
   缺，自己创建个文件夹就好   
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: "baotongnoob"<notifications@github.com&amp;amp;amp;gt;;    
   发送时间: 2020年3月12日(星期四) 下午2:49   
   收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;amp;gt;;    
   抄送: "Lambda"<894463634@qq.com&amp;amp;amp;gt;; "Author"<author@noreply.github.com&amp;amp;amp;gt;;    
   主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)   
     
     
     
     
     
       
   你预测的时候缺文件嘛

**Comment by foreverxujiahuan** [comment]
陌生文本全打O啊，然后人肉看效果


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"baotongnoob"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 下午3:35
收件人:&nbsp;"ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&gt;;
抄送:&nbsp;"Lambda"<894463634@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)





 怎么预测陌生的文本&amp;nbsp; 它的测试集也打了标签的 然后预测的东西是测试集里的话&amp;nbsp; 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "zzulixjh"<notifications@github.com&amp;gt;;  
 发送时间: 2020年3月12日(星期四) 下午3:32 
 收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;gt;;  
 抄送: "baotong"<448276274@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57) 
 
 
 
 
 
  不用改代码，保证BIO数据没问题就行  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"baotongnoob"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年3月12日(星期四) 下午3:30  
  收件人:&amp;amp;nbsp;"ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"Lambda"<894463634@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)  
   
   
   
   
   
   wow,你在houston啊。那你当时换了自己标注的数据集 改了部分代码吗 还是直接上BIO标注的数据就行   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: "zzulixjh"<notifications@github.com&amp;amp;amp;gt;;    
   发送时间: 2020年3月12日(星期四) 下午3:28   
   收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;amp;gt;;    
   抄送: "baotong"<448276274@qq.com&amp;amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;amp;gt;;    
   主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)   
     
     
     
     
     
    缺，自己创建个文件夹就好    
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人: "baotongnoob"<notifications@github.com&amp;amp;amp;amp;gt;;     
    发送时间: 2020年3月12日(星期四) 下午2:49    
    收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;amp;amp;gt;;     
    抄送: "Lambda"<894463634@qq.com&amp;amp;amp;amp;gt;; "Author"<author@noreply.github.com&amp;amp;amp;amp;gt;;     
    主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)    
       
       
       
       
       
         
    你预测的时候缺文件嘛

**Comment by tongbao96** [comment]
我能加你微信不




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zzulixjh"<notifications@github.com&gt;; 
发送时间: 2020年3月12日(星期四) 下午3:36
收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&gt;; 
抄送: "baotong"<448276274@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)





 陌生文本全打O啊，然后人肉看效果 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"baotongnoob"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月12日(星期四) 下午3:35 
 收件人:&amp;nbsp;"ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Lambda"<894463634@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57) 
 
 
 
 
 
  怎么预测陌生的文本&amp;amp;nbsp; 它的测试集也打了标签的 然后预测的东西是测试集里的话&amp;amp;nbsp;  
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "zzulixjh"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2020年3月12日(星期四) 下午3:32  
  收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;gt;;   
  抄送: "baotong"<448276274@qq.com&amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;gt;;   
  主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)  
   
   
   
   
   
   不用改代码，保证BIO数据没问题就行   
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:&amp;amp;amp;nbsp;"baotongnoob"<notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年3月12日(星期四) 下午3:30   
   收件人:&amp;amp;amp;nbsp;"ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"Lambda"<894463634@qq.com&amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)   
     
     
     
     
     
    wow,你在houston啊。那你当时换了自己标注的数据集 改了部分代码吗 还是直接上BIO标注的数据就行    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人: "zzulixjh"<notifications@github.com&amp;amp;amp;amp;gt;;     
    发送时间: 2020年3月12日(星期四) 下午3:28    
    收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;amp;amp;gt;;     
    抄送: "baotong"<448276274@qq.com&amp;amp;amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;amp;amp;gt;;     
    主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)    
       
       
       
       
       
     缺，自己创建个文件夹就好     
         
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人: "baotongnoob"<notifications@github.com&amp;amp;amp;amp;amp;gt;;      
     发送时间: 2020年3月12日(星期四) 下午2:49     
     收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;amp;amp;amp;gt;;      
     抄送: "Lambda"<894463634@qq.com&amp;amp;amp;amp;amp;gt;; "Author"<author@noreply.github.com&amp;amp;amp;amp;amp;gt;;      
     主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)     
         
         
         
         
         
           
     你预测的时候缺文件嘛

**Comment by foreverxujiahuan** [comment]
XJH15712615165


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"baotongnoob"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 下午3:37
收件人:&nbsp;"ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&gt;;
抄送:&nbsp;"Lambda"<894463634@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)





 我能加你微信不 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "zzulixjh"<notifications@github.com&amp;gt;;  
 发送时间: 2020年3月12日(星期四) 下午3:36 
 收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;gt;;  
 抄送: "baotong"<448276274@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57) 
 
 
 
 
 
  陌生文本全打O啊，然后人肉看效果  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"baotongnoob"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年3月12日(星期四) 下午3:35  
  收件人:&amp;amp;nbsp;"ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"Lambda"<894463634@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)  
   
   
   
   
   
   怎么预测陌生的文本&amp;amp;amp;nbsp; 它的测试集也打了标签的 然后预测的东西是测试集里的话&amp;amp;amp;nbsp;   
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: "zzulixjh"<notifications@github.com&amp;amp;amp;gt;;    
   发送时间: 2020年3月12日(星期四) 下午3:32   
   收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;amp;gt;;    
   抄送: "baotong"<448276274@qq.com&amp;amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;amp;gt;;    
   主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)   
     
     
     
     
     
    不用改代码，保证BIO数据没问题就行    
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:&amp;amp;amp;amp;nbsp;"baotongnoob"<notifications@github.com&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2020年3月12日(星期四) 下午3:30    
    收件人:&amp;amp;amp;amp;nbsp;"ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;amp;amp;gt;;    
    抄送:&amp;amp;amp;amp;nbsp;"Lambda"<894463634@qq.com&amp;amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)    
       
       
       
       
       
     wow,你在houston啊。那你当时换了自己标注的数据集 改了部分代码吗 还是直接上BIO标注的数据就行     
         
         
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人: "zzulixjh"<notifications@github.com&amp;amp;amp;amp;amp;gt;;      
     发送时间: 2020年3月12日(星期四) 下午3:28     
     收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;amp;amp;amp;gt;;      
     抄送: "baotong"<448276274@qq.com&amp;amp;amp;amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;amp;amp;amp;gt;;      
     主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)     
         
         
         
         
         
      缺，自己创建个文件夹就好      
           
           
           
      ------------------&amp;amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;amp;nbsp;------------------      
      发件人: "baotongnoob"<notifications@github.com&amp;amp;amp;amp;amp;amp;gt;;       
      发送时间: 2020年3月12日(星期四) 下午2:49      
      收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;amp;amp;amp;amp;gt;;       
      抄送: "Lambda"<894463634@qq.com&amp;amp;amp;amp;amp;amp;gt;; "Author"<author@noreply.github.com&amp;amp;amp;amp;amp;amp;gt;;       
      主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57)      
           
           
           
           
           
             
      你预测的时候缺文件嘛

**Comment by dengxuanxiang** [comment]
> XJH15712615165
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"baotongnoob"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月12日(星期四) 下午3:37 收件人:&nbsp;"ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&gt;; 抄送:&nbsp;"Lambda"<894463634@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57) 我能加你微信不
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "zzulixjh"<notifications@github.com&amp;gt;; 发送时间: 2020年3月12日(星期四) 下午3:36 收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;gt;; 抄送: "baotong"<448276274@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;; 主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57) 陌生文本全打O啊，然后人肉看效果
> ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 发件人:&amp;amp;nbsp;"baotongnoob"<notifications@github.com&amp;amp;gt;; 发送时间:&amp;amp;nbsp;2020年3月12日(星期四) 下午3:35 收件人:&amp;amp;nbsp;"ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;gt;; 抄送:&amp;amp;nbsp;"Lambda"<894463634@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;; 主题:&amp;amp;nbsp;Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57) 怎么预测陌生的文本&amp;amp;amp;nbsp; 它的测试集也打了标签的 然后预测的东西是测试集里的话&amp;amp;amp;nbsp;
> ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------ 发件人: "zzulixjh"<notifications@github.com&amp;amp;amp;gt;; 发送时间: 2020年3月12日(星期四) 下午3:32 收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;amp;gt;; 抄送: "baotong"<448276274@qq.com&amp;amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;amp;gt;; 主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57) 不用改代码，保证BIO数据没问题就行
> ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------ 发件人:&amp;amp;amp;amp;nbsp;"baotongnoob"<notifications@github.com&amp;amp;amp;amp;gt;; 发送时间:&amp;amp;amp;amp;nbsp;2020年3月12日(星期四) 下午3:30 收件人:&amp;amp;amp;amp;nbsp;"ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;amp;amp;gt;; 抄送:&amp;amp;amp;amp;nbsp;"Lambda"<894463634@qq.com&amp;amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;amp;gt;; 主题:&amp;amp;amp;amp;nbsp;Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57) wow,你在houston啊。那你当时换了自己标注的数据集 改了部分代码吗 还是直接上BIO标注的数据就行
> ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------ 发件人: "zzulixjh"<notifications@github.com&amp;amp;amp;amp;amp;gt;; 发送时间: 2020年3月12日(星期四) 下午3:28 收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;amp;amp;amp;gt;; 抄送: "baotong"<448276274@qq.com&amp;amp;amp;amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;amp;amp;amp;gt;; 主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57) 缺，自己创建个文件夹就好
> ------------------&amp;amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;amp;nbsp;------------------ 发件人: "baotongnoob"<notifications@github.com&amp;amp;amp;amp;amp;amp;gt;; 发送时间: 2020年3月12日(星期四) 下午2:49 收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&amp;amp;amp;amp;amp;amp;gt;; 抄送: "Lambda"<894463634@qq.com&amp;amp;amp;amp;amp;amp;gt;; "Author"<author@noreply.github.com&amp;amp;amp;amp;amp;amp;gt;; 主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57) 你预测的时候缺文件嘛 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> 缺，自己创建个文件夹就好
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "baotongnoob"<notifications@github.com&gt;; 发送时间: 2020年3月12日(星期四) 下午2:49 收件人: "ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&gt;; 抄送: "Lambda"<894463634@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [ProHiryu/bert-chinese-ner] 结果全为O问题 (#57) 你预测的时候缺文件嘛 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，请问你在训练的时候是不是一直会显示训练日志，类似Tensorflow Info这样的输出

**Comment by dengxuanxiang** [comment]
请问训练的时候是不是一直会显示训练日志，例如tensorflow Info这样的输出
