### ISSUE TITLE
请问一下您的环境是py2吗？

### ISSUE THREAD

**Issue by littleys** [ProHiryu/bert-chinese-ner#59]
我py3运行一直报错，改半天了

**Comment by tongbao96** [comment]
我也在run这个  能加你微信吗

**Comment by littleys** [comment]
18811783956！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"baotongnoob"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 上午9:51
收件人:&nbsp;"ProHiryu/bert-chinese-ner"<bert-chinese-ner@noreply.github.com&gt;;
抄送:&nbsp;"闫硕"<1501877940@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ProHiryu/bert-chinese-ner] 请问一下您的环境是py2吗？ (#59)





 
我也在run这个  能加你微信吗

**Comment by ProHiryu** [comment]
python 3.6, 报错可能是tensorflow

**Comment by foreverxujiahuan** [comment]
tf版本多少?

**Comment by umbrellaaaa** [comment]
> 我py3运行一直报错，改半天了

我也一直报错....你解决了吗

**Comment by tongbao96** [comment]
> 错....你解决了吗

我也是 哈
