### ISSUE TITLE
How to save the model with the best f1 score in verification when training in multiple rounds？

### ISSUE THREAD

**Issue by sxk000** [ProHiryu/bert-chinese-ner#62]
How to save the model with the best f1 score in verification when training in multiple rounds ？

**Comment by ProHiryu** [comment]
just keep tracking the scores and stop training in your extremum

**Comment by sxk000** [comment]
@ProHiryu thanks,could you point it where and how to do it ?

**Comment by ProHiryu** [comment]
In your code, when the scores going down, just stop training
