### ISSUE TITLE
The label_map starts from 1 not 0. How do you avoid getting predicted label == 0

### ISSUE THREAD

**Issue by nlpconf** [ProHiryu/bert-chinese-ner#63]
The label_map keys starts from 1. But when predicting, I think it may possible get a predicted label_id that equals 0 and this will generate a key err when it calls label_map[label_id]. Did I miss anything here?

**Comment by ProHiryu** [comment]
Just ignore 0 and start from 1, 0 means padding, it is nothing here for predict
