### ISSUE TITLE
请问，如何使用tenorflow-serving 进行相应的部署呢。您有相关资料或代码吗？

### ISSUE THREAD

**Issue by SevenMpp** [ProHiryu/bert-chinese-ner#69]
我进行了bert NER的fine-tune 后得到了ckpt的模型，但是我想部署这些模型并进行预测。请问这个应该如何做呢，您可以帮助下吗？

**Comment by modispy** [comment]
同问，我转成pb部署后，不知道咋调用

**Comment by ProHiryu** [comment]
参考一下https://blog.csdn.net/huanghaocs/article/details/111939507 看看
