### ISSUE TITLE
label中为什么有个X

### ISSUE THREAD

**Issue by myeclipse** [ProHiryu/bert-chinese-ner#8]
![image](https://user-images.githubusercontent.com/6872419/51605887-46a90100-1f4b-11e9-9422-066ee3df7ca3.png)

**Comment by myeclipse** [comment]
OOV的词吗

**Comment by ProHiryu** [comment]
Bert自动分词的，分出来的token形如：["do", "ing"]，这样子，为了避免token出错，出现多个字在同一个list当中，需要加入X这个容错机制，防止label和inputs长度不同，可以理解为中文当中是没用的。

**Comment by xljhtq** [comment]
@ProHiryu 照理bert tokenize出来的就是字呀，怎么会有多余的字在token这个list中呢？请解释一下，而且demo中的训练文本也没有打印出这个特例。。

**Comment by Robets2020** [comment]
主要是英文下用的比如doing会分成do ##ing,   tag只算在前面那个词上, 后面那个词的tag就是X

**Comment by icecity96** [comment]
@roberts-sh 所以X这个tag再中文环境下其实是没用的？

**Comment by ProHiryu** [comment]
中文当中X并不存在实际意义 @icecity96 , 已经更新代码

**Comment by alphanlp** [comment]
中文一般都会混合英文，去掉会有潜在bug风险，建议加上

**Comment by ProHiryu** [comment]
@shisi2015 多谢提醒
