### ISSUE TITLE
提个bug

### ISSUE THREAD

**Issue by myeclipse** [ProHiryu/bert-chinese-ner#9]
![image](https://user-images.githubusercontent.com/6872419/51730889-1a5cc400-20b4-11e9-8025-db833505f20e.png)
标注数据中每句话的结尾不一定是句号

**Comment by myeclipse** [comment]
![image](https://user-images.githubusercontent.com/6872419/51730936-4a0bcc00-20b4-11e9-9cb0-9260b65f6797.png)

**Comment by ProHiryu** [comment]
已修改，谢谢～
